version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: sql_playground
    environment:
      POSTGRES_USER: sqluser
      POSTGRES_PASSWORD: sqlpass
      POSTGRES_DB: playground
    ports:
      - "5433:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
